spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/flea_market?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8000

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.suda.fleamarket.entity

